#!/usr/bin/env bash
set -euo pipefail

SERVER_HOST="${SERVER_HOST:-}"
REPO_DIR="${REPO_DIR:-/srv/caipu-miniapp}"
BACKEND_DIR="${BACKEND_DIR:-${REPO_DIR}/backend}"
BINARY_PATH="${BINARY_PATH:-${BACKEND_DIR}/bin/server}"
SERVICE_NAME="${SERVICE_NAME:-caipu-backend}"
APP_PORT="${APP_PORT:-8080}"
HEALTHCHECK_PATH="${HEALTHCHECK_PATH:-/healthz}"
SYSTEMCTL_BIN="${SYSTEMCTL_BIN:-systemctl}"
BUILD_NICE="${BUILD_NICE:-10}"
GO_BUILD_GOMAXPROCS="${GO_BUILD_GOMAXPROCS:-1}"
PLAN_ONLY="${PLAN_ONLY:-0}"

if [[ -z "$SERVER_HOST" ]]; then
  echo "SERVER_HOST is required, for example: root@1.2.3.4" >&2
  exit 1
fi

ssh "$SERVER_HOST" \
  "REPO_DIR='$REPO_DIR' BACKEND_DIR='$BACKEND_DIR' BINARY_PATH='$BINARY_PATH' SERVICE_NAME='$SERVICE_NAME' APP_PORT='$APP_PORT' HEALTHCHECK_PATH='$HEALTHCHECK_PATH' SYSTEMCTL_BIN='$SYSTEMCTL_BIN' BUILD_NICE='$BUILD_NICE' GO_BUILD_GOMAXPROCS='$GO_BUILD_GOMAXPROCS' PLAN_ONLY='$PLAN_ONLY' bash -s" <<'REMOTE'
set -euo pipefail

cd "$REPO_DIR"
bash scripts/deploy-backend-on-server.sh
REMOTE
